name: Deploy-Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set proper file ownership on the server
        run: |
          ssh -i ${{ secrets.EC2_SSH_KEY }} ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }} 'sudo chown -R $USER:$USER /var/www/html && sudo chmod -R 755 /var/www/html'

      - name: Deploy to Backend Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.BACKEND_HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY_BACK }}
          script: |
            cd ~
            rsync -av --delete ~/ /var/www/html/
            sudo apt update && sudo apt upgrade -y
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt install -y nodejs npm pm2 nginx
            cd /var/www/html
            sudo npm install
            pm2 start npm --name "backend" -- start
            pm2 save
            pm2 startup
            sudo systemctl restart nginx
