name: Deploy-Frontend
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Frontend Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS_FRONT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY_FRONT }}
          script: |
            # Define project directory
            PROJECT_DIR=/var/www/frontend
            USER=${{ secrets.USERNAME }}

            # Ensure the directory exists
            sudo mkdir -p $PROJECT_DIR
            sudo chown -R $USER:$USER $PROJECT_DIR

            # Use rsync correctly (excluding system files)
            # rsync -av --delete --exclude='.bash*' --exclude='.npm' ./ $PROJECT_DIR/
            rsync -av --delete --exclude='.bash*' --exclude='.npm' ./ home/

            # Install dependencies & build
            # cd $PROJECT_DIR
            cd home
            sudo apt update && sudo apt upgrade -y
            npm install
            npm run build

            # Serve with PM2
            sudo npm install -g pm2 serve
            pm2 delete frontend || true  # Ensure previous instance is stopped
            pm2 start "serve -s build -p 8080" --name "frontend"            

            # Restart Nginx
            sudo systemctl restart nginx

      - name: Set proper file ownership on the server
        run: |
          sudo chown -R $USER:$USER /var/www/frontend
          sudo chmod -R 755 /var/www/frontend
          sudo systemctl restart nginx
