name: Deploy-Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Backend Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS_BACK }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY_BACK }}
          script: |
            # Define project directory
            PROJECT_DIR="/var/www/backend"
            sudo chown -R ${{ secrets.USERNAME }}:${{ secrets.USERNAME }} $PROJECT_DIR

            # Debug output
            echo "Debug: USER is set to '$USER'"

            # Ensure directory exists with correct permissions
            sudo mkdir -p $PROJECT_DIR
            sudo chown -R $USER:$USER $PROJECT_DIR
            sudo chmod -R 755 $PROJECT_DIR

            # Restart nginx (before deploying to free up any locked resources)
            sudo systemctl restart nginx || true

            # Sync backend files properly (fix incorrect rsync path)
            rsync -av --delete --exclude='.bash*' --exclude='.npm' ./backend/ $PROJECT_DIR/

            # Check if package.json exists
            if [ ! -f "$PROJECT_DIR/package.json" ]; then
              echo "ERROR: package.json missing in $PROJECT_DIR"
              exit 1
            fi

            # Update system and install dependencies
            sudo apt update && sudo apt upgrade -y
            cd $PROJECT_DIR
            sudo npm install

            # Install PM2 properly
            sudo npm install -g pm2
            export PATH=$PATH:/usr/local/bin

            # Restart backend using PM2
            pm2 delete backend || true
            pm2 start npm --name "backend" -- start
            pm2 save
            pm2 startup

            # Restart nginx to apply changes
            sudo systemctl restart nginx
